title: Welcome to Sustance
description: > # this means to ignore newlines until "baseurl:"
  This eclectic collection of things I find useful. They are shared here in case others feel the same.
permalink: ':title/'
baseurl: "/sustance.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sustance # add your name
author-img: bird.jpg # add your photo
about-author: I am a information enthusiast. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
#social-github: artemsheludko # add your Github handle
#ocial-linkedin: # add your Linkedin handle
#social-email: # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
